name: Pull Request Check

on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ktlint:
    uses: ./.github/workflows/pullRequestCheck/ktlint.yaml

  android-lint:
    uses: ./.github/workflows/pullRequestCheck/androidLint.yaml

  kover:
    uses: ./.github/workflows/pullRequestCheck/kover.yaml
    with:
      pull_request_number: ${{ github.event.number }}
