name: Pull Request Check

on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  pull-requests: write
  contents: write

jobs:
  ktlint:
    uses: ./.github/workflows/pullRequestCheckKtlint.yaml

  android-lint:
    uses: ./.github/workflows/pullRequestCheckAndroidLint.yaml

  kover:
    uses: ./.github/workflows/pullRequestCheckKover.yaml
    with:
      pull_request_number: ${{ github.event.number }}
